info:
  component: Config server

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/Git/cloud-config

server:
  address: ${spring.application.name}.vinsign.vintegris.net
  port: 8888
  ssl:
    key-store: C:/server/ftp/certs/${spring.application.name}.vinsign.vintegris.net.jks
    key-store-password: Vintegris90
    key-password: Vintegris90

management:
  security:
    enabled: false

eureka:
  environment: test
  datacenter: test
  instance:
    hostname: ${server.address}
    instanceId: ${server.address}:${spring.application.name}:${server.port}
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/
    statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discover.vinsign.vintegris.net:8761/eureka/
