spring:
  application:
    name: sign
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      failFast : true
management:
  security:
    enabled: false
server:
  port: 9000
message: My name is Sign
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/