spring:
  application:
    name: sign
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config
      failFast: true
management:
  security:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
server:
  port: 9000