info:
  component: Eureka server

spring:
  application:
    name: discover

server:
  address: ${spring.application.name}.vinsign.vintegris.net
  port: 8761
  ssl:
    enabled: true
    key-store: C:/server/ftp/certs/${spring.application.name}.vinsign.vintegris.net.jks
    key-store-password: Vintegris90
    key-password: Vintegris90

management:
  security:
    enabled: false

eureka:
  environment: test
  datacenter: test
  instance:
    hostname: ${server.address}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/
    statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.securePort}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
